'use strict';
// This file is used as a common base config for the production and development configs.

var path = require('path'),
    webpack = require('webpack'),
    autoprefixer = require('autoprefixer'),
    Clean = require('clean-webpack-plugin'),
    CopyWebpackPlugin = require('copy-webpack-plugin'),
    HtmlWebpackPlugin = require('html-webpack-plugin'),
    ExtractTextPlugin = require('extract-text-webpack-plugin'),
    buildDir = path.join(__dirname, 'dist');

var config = {
    entry: {
        'app': [
            path.join(__dirname, 'app/client/assets/js/app.js')
        ]
    },
    externals: { 
        "jquery": "jQuery"
    },
    module: {
        preLoaders: [
        ],
        loaders: [
            {
                test: /\.html$/,
                loader: 'ng-cache-loader?prefix=[dir]/[dir]!html-minify',
                exclude: path.join(__dirname, 'app/client/assets/index.template.html')
            },
            {
                test: /\.css$/,
                loader: ExtractTextPlugin.extract('style-loader', 'css-loader!postcss-loader')
            },
            {
                test: /\.less$/,
                loader: ExtractTextPlugin.extract('style-loader', 'css-loader!postcss-loader!less-loader')
            },
            { 
                test: /\.(ttf|eot|woff(2)?)(\?v=[0-9]\.[0-9]\.[0-9])?$/, 
                loader: 'file-loader' 
            },
			{
				test: /\.(gif|jpg|svg|png)$/,
				loader: 'url-loader'
			}
        ]
    },
    output: {
        filename: '[name].[hash].min.js',
        chunkFilename: '[hash].js',
        path: buildDir,
        publicPath: '/'
    },
    plugins: [
        new Clean(buildDir),
        new webpack.optimize.OccurrenceOrderPlugin(true),
        new ExtractTextPlugin('[name].[hash].min.css'),
        new HtmlWebpackPlugin({
            template: path.join(__dirname, 'app/client/assets/index.template.html'),
            favicon: path.join(__dirname, 'app/client/assets/images/favicon.ico'),
            inject: 'body',
            filename: 'index.html',
            minify: {
                caseSensitive: true,
                collapseBooleanAttributes: true,
                collapseWhitespace: true,
                includeAutoGeneratedTags: true,
                keepClosingSlash: true,
                minifyJS: true,
                minifyCSS: true,
                removeCDATASectionsFromCDATA: true,
                removeComments: true,
                removeCommentsFromCDATA: true,
                removeEmptyAttributes: true,
                removeRedundantAttributes: true,
                removeScriptTypeAttributes: true,
                removeStyleLinkTypeAttributes: true,
                removeTagWhitespace: false,
                useShortDoctype: true
            }
        }),
        new CopyWebpackPlugin ([
            { from: 'app/client/assets/images', to: 'images' },
            { from: 'app/client/assets/fonts', to: 'fonts' },
            { from: 'app/client/assets/js/vendor', to: 'js/vendor' },
            { from: 'app/client/assets/files', to: 'files' }
        ])
    ],
    postcss: [
        autoprefixer({ browsers: ['last 10 versions', '> 10%', '> 5% in US', 'Explorer >= 9'] })
    ]
};

module.exports = config;